// ============================================================
// CONFIGURAÇÃO DO LEAD RADAR
// ============================================================

// --- Supabase ---
const SUPABASE_URL = "https://gmpmgzmvaizmlcalsdbg.supabase.co";
const SUPABASE_KEY = "sb_publishable_zJc5jsET_UK6wu4nyd5vUQ_bUWhZYfb";

// --- Mapa de tipos de negócio (PT-BR) -> tags do OpenStreetMap ---
// Cada entrada gera cláusulas "chave=valor" usadas na consulta Overpass.
// Além das tags, sempre fazemos também uma busca por nome (regex) para pegar
// estabelecimentos mal categorizados no mapa.
const TAG_MAP = {
  "barbearia": ["shop=hairdresser", "shop=barber"],
  "salão de beleza": ["shop=beauty", "shop=hairdresser"],
  "salao de beleza": ["shop=beauty", "shop=hairdresser"],
  "pet shop": ["shop=pet"],
  "petshop": ["shop=pet"],
  "clínica veterinária": ["amenity=veterinary"],
  "clinica veterinaria": ["amenity=veterinary"],
  "restaurante": ["amenity=restaurant"],
  "lanchonete": ["amenity=fast_food"],
  "pizzaria": ["amenity=restaurant", "cuisine=pizza"],
  "academia": ["leisure=fitness_centre"],
  "estúdio de yoga": ["leisure=fitness_centre", "sport=yoga"],
  "farmácia": ["amenity=pharmacy"],
  "farmacia": ["amenity=pharmacy"],
  "oficina mecânica": ["shop=car_repair"],
  "oficina mecanica": ["shop=car_repair"],
  "borracharia": ["shop=tyres"],
  "clínica odontológica": ["amenity=dentist"],
  "clinica odontologica": ["amenity=dentist"],
  "dentista": ["amenity=dentist"],
  "consultório médico": ["amenity=doctors"],
  "consultorio medico": ["amenity=doctors"],
  "clínica de estética": ["shop=beauty"],
  "clinica de estetica": ["shop=beauty"],
  "mercado": ["shop=supermarket", "shop=convenience"],
  "mercearia": ["shop=convenience"],
  "padaria": ["shop=bakery"],
  "confeitaria": ["shop=bakery", "shop=pastry"],
  "loja de roupas": ["shop=clothes"],
  "boutique": ["shop=clothes", "shop=boutique"],
  "loja de calçados": ["shop=shoes"],
  "imobiliária": ["office=estate_agent"],
  "imobiliaria": ["office=estate_agent"],
  "escritório de advocacia": ["office=lawyer"],
  "escritorio de advocacia": ["office=lawyer"],
  "advogado": ["office=lawyer"],
  "contabilidade": ["office=accountant"],
  "contador": ["office=accountant"],
  "auto escola": ["amenity=driving_school"],
  "autoescola": ["amenity=driving_school"],
  "floricultura": ["shop=florist"],
  "papelaria": ["shop=stationery"],
  "loja de móveis": ["shop=furniture"],
  "loja de moveis": ["shop=furniture"],
  "loja de eletrônicos": ["shop=electronics"],
  "loja de eletronicos": ["shop=electronics"],
  "assistência técnica": ["shop=electronics", "shop=mobile_phone", "craft=electronics_repair"],
  "assistencia tecnica": ["shop=electronics", "shop=mobile_phone", "craft=electronics_repair"],
  "loja de celulares": ["shop=mobile_phone"],
  "hotel": ["tourism=hotel"],
  "pousada": ["tourism=guest_house"],
  "posto de gasolina": ["amenity=fuel"],
  "lavanderia": ["shop=laundry"],
  "loja de materiais de construção": ["shop=hardware", "shop=doityourself"],
  "loja de materiais de construcao": ["shop=hardware", "shop=doityourself"],
  "marcenaria": ["craft=carpenter"],
  "serralheria": ["craft=metal_construction"],
  "fotógrafo": ["craft=photographer", "shop=photo"],
  "fotografo": ["craft=photographer", "shop=photo"],
  "buffet": ["amenity=restaurant", "shop=catering"],
  "sorveteria": ["amenity=ice_cream"],
  "cafeteria": ["amenity=cafe"],
  "café": ["amenity=cafe"],
  "loja de ótica": ["shop=optician"],
  "otica": ["shop=optician"],
  "loja de brinquedos": ["shop=toys"],
  "livraria": ["shop=books"],
  "clínica de fisioterapia": ["healthcare=physiotherapist"],
  "clinica de fisioterapia": ["healthcare=physiotherapist"],
  "fisioterapeuta": ["healthcare=physiotherapist"],
};

// Fallback: se o termo digitado não estiver no mapa acima, fazemos apenas
// busca textual pelo nome do estabelecimento (regex, sem acento-sensível).

// --- Bounding boxes aproximados dos estados brasileiros (south, west, north, east) ---
// Usados para a opção "Brasil inteiro" (percorre estado por estado).
const BRAZIL_STATES = [
  { uf: "AC", nome: "Acre", bbox: [-11.14, -73.99, -7.35, -66.62] },
  { uf: "AL", nome: "Alagoas", bbox: [-10.5, -38.24, -8.81, -35.15] },
  { uf: "AP", nome: "Amapá", bbox: [-1.24, -54.88, 4.44, -49.88] },
  { uf: "AM", nome: "Amazonas", bbox: [-9.82, -73.8, 2.25, -56.09] },
  { uf: "BA", nome: "Bahia", bbox: [-18.35, -46.62, -8.53, -37.34] },
  { uf: "CE", nome: "Ceará", bbox: [-7.87, -41.42, -2.78, -37.25] },
  { uf: "DF", nome: "Distrito Federal", bbox: [-16.05, -48.28, -15.5, -47.31] },
  { uf: "ES", nome: "Espírito Santo", bbox: [-21.31, -41.88, -17.89, -39.65] },
  { uf: "GO", nome: "Goiás", bbox: [-19.5, -53.25, -12.39, -45.9] },
  { uf: "MA", nome: "Maranhão", bbox: [-10.26, -48.76, -1.04, -41.79] },
  { uf: "MT", nome: "Mato Grosso", bbox: [-18.04, -61.63, -7.35, -50.22] },
  { uf: "MS", nome: "Mato Grosso do Sul", bbox: [-24.07, -58.17, -17.17, -50.92] },
  { uf: "MG", nome: "Minas Gerais", bbox: [-22.92, -51.05, -14.23, -39.86] },
  { uf: "PA", nome: "Pará", bbox: [-9.84, -58.9, 2.59, -46.06] },
  { uf: "PB", nome: "Paraíba", bbox: [-8.32, -38.76, -6.02, -34.79] },
  { uf: "PR", nome: "Paraná", bbox: [-26.72, -54.62, -22.51, -48.02] },
  { uf: "PE", nome: "Pernambuco", bbox: [-9.48, -41.36, -7.29, -34.8] },
  { uf: "PI", nome: "Piauí", bbox: [-10.93, -45.99, -2.74, -40.37] },
  { uf: "RJ", nome: "Rio de Janeiro", bbox: [-23.37, -44.89, -20.76, -40.96] },
  { uf: "RN", nome: "Rio Grande do Norte", bbox: [-6.98, -38.58, -4.83, -34.97] },
  { uf: "RS", nome: "Rio Grande do Sul", bbox: [-33.75, -57.65, -27.08, -49.69] },
  { uf: "RO", nome: "Rondônia", bbox: [-13.69, -66.81, -7.97, -59.77] },
  { uf: "RR", nome: "Roraima", bbox: [-1.58, -64.82, 5.27, -58.87] },
  { uf: "SC", nome: "Santa Catarina", bbox: [-29.35, -53.84, -25.95, -48.35] },
  { uf: "SP", nome: "São Paulo", bbox: [-25.31, -53.11, -19.78, -44.16] },
  { uf: "SE", nome: "Sergipe", bbox: [-11.57, -38.24, -9.51, -36.39] },
  { uf: "TO", nome: "Tocantins", bbox: [-13.46, -50.74, -5.17, -45.7] },
];